//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 1/20/2024 11:38:04 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Text.Json.Serialization;
using Newtonsoft.Json;

namespace TillApp.Shared.Models
{
    public partial class Order
    {
        public int OrderID { get; set; }

        public string OrderName { get; set; }

        public decimal Amount { get; set; }

        public bool IsPaid { get; set; }

        public virtual List<OrderItem> OrderItems { get; set; }
    }

}
